### PR TITLE
i18n of Spanish and Galician

### PR DESCRIPTION
**Pull request by Ran-n**
#21 
Also the updated setup.md since the change is still on the repository xd

### CODE REVIEW

**Comment by Ran-n** [comment]
Also adding the shortcode moeda with what we discussed in #10 about putting icons for some coins.
The script added in that file makes it so it gets autocopied to clipboard when the icon is clicked.

Its a bit hacky since you will load the script each time the shortcode is used, it should be improved so it doesnt and also so it is on a separate js file.

**Comment by Ran-n** [comment]
separated a couple of commands on the setup page for a better experience and added a script to launch the server if you want to bind it to a name

**Comment by Ran-n** [comment]
Solved #27 by adding the option "bookcase_hide" (with default to false, not hide).
I went with true/false instead of 1/0 to keep the theme of the rest of the options.

**Comment by kaiiiz** [comment]
Thanks for the contribution in advance. But please separate the patch for different purposes into different pull requests for ease of maintenance. Here are some comments about the patch:

1. i18n & document improvement are welcome.
2. Additional script should not be included: `exampleSite/run.sh`.
3. New shortcode should include a well-described document for each parameter and usage examples.
4. The parameter name should be English for consistency.

**Pull request closed without merging**
